#!/usr/bin/env perl

use strict;
use warnings;
use FindBin '$Bin';
use Getopt::Std;

our($opt_a);
getopts('a');

my $TTREE = '/usr/local/bin/ttree';
my $rcfilebase = 'gen-static-pages.ttreerc';
my $RCFILE = join '/', $Bin, $rcfilebase;

chdir $Bin or die "error changing default director to $Bin: $!";

unless (-f $RCFILE) {
    die "non-existent rc file: $RCFILE";
}

my $CATALYST_APP_NAME = 'Harvest';   # Must be set to Template::CatalystConfig can find the .conf file(s)!
my $CFGPATH = "$FindBin::Bin/../..";
my $PERL5LIB = "$FindBin::Bin/../../lib";
my $TTREERC = $RCFILE;

my $ENV = "PERL5LIB=${PERL5LIB} TTREERC=${TTREERC} CATALYST_APP_NAME=${CATALYST_APP_NAME} CFGPATH=${CFGPATH}";
my $OPTIONS = '--template_module=Template::CatalystConfig';     # use a Template subclass that adds the Catalyst config in the 'c' stash namespace

if($opt_a) {
    system("$ENV $TTREE $OPTIONS -a");
    print "ttree using rc file (ALL option ON): $RCFILE\n";
}
else {
    system("$ENV $TTREE $OPTIONS");
    print "ttree using rc file: $RCFILE\n";
}

